# Generated by Django 4.1 on 2022-09-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic_src',
            field=models.CharField(default='dummy', max_length=255),
            preserve_default=False,
        ),
    ]
