# Generated by Django 4.1 on 2022-09-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_user_pic_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Timestamp',
            new_name='timestamp',
        ),
    ]
